base_config: ./config
base_expid: STEM_TiktokLarge
dataset_id: TiktokLarge

tuner_space:
    model_root: './checkpoints/TiktokLarge/TiktokLarge_STEM_tuner'
    num_shared_experts: [1,2,4,8]
    num_specific_experts: [1,2,4]
    expert_hidden_units: [[512,512,512]]
    gate_hidden_units: [[128, 64]]
    tower_hidden_units: [[128, 64]]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: [1.e-6, 1.e-5, 1.e-4, 1.e-3, 5.e-6, 5.e-5, 5.e-4, 5.e-3]
    net_dropout: [0, 0.1, 0.2, 0.3]
    batch_norm: False
    learning_rate: [1.e-4]
    batch_size: 4096
    seed: [2023, 76, 525, 728, 42]
    group_id: uid
    metrics: [[gAUC, AUC, logloss]]
    monitor: {"gAUC": 0, "AUC": 1}
